server:
  port: 8080

es:
  url: ${ES_URL:https://31a8c5124ac34f5cb1796eb7065b67d9.us-central1.gcp.cloud.es.io:443}   # override via env var ES_URL
  apiKey: ${ES_API_KEY:a0FYQjY1d0JsTnJkTzQtTDNpbUI6ckdnUGdicGFXQ1BteXFETTFnaWJOQQ==}              # REQUIRED: base64(id:key)

spring:
  main:
    banner-mode: "off"