server:
  port: 8080

es:
  url: ${ES_URL:https://c908f2497167445385e8b342d3ad51a7.asia-south1.gcp.elastic-cloud.com:443}   # override via env var ES_URL
  apiKey: ${ES_API_KEY:ZWZSN29KMEJyelJwZS0xekhBYTM6N0dqeFdoUEhhaWNBY2w2dnNBMl9Idw==}        # REQUIRED: base64(id:key)

spring:
  main:
    banner-mode: "off"
  security:
    oauth2:
      resourceserver:
        jwt:
          # Identity Platform / Firebase issuer
          issuer-uri: https://securetoken.google.com/${GCP_PROJECT_ID:nagp-demo-487019}
          # Optional: give Spring an explicit JWKs endpoint if discovery fails at startup
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com